// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT4w25EL2FaM0SPlxtYP0zNvlXjTDCXk8',
    appId: '1:443807882531:web:a2202d6d0b9e30bfc68096',
    messagingSenderId: '443807882531',
    projectId: 'ugiconnect-f3e0f',
    authDomain: 'ugiconnect-f3e0f.firebaseapp.com',
    storageBucket: 'ugiconnect-f3e0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaeLLvbvQX-7R9u339922wumMqnTBm3oE',
    appId: '1:443807882531:android:cd94c3777efcb4aec68096',
    messagingSenderId: '443807882531',
    projectId: 'ugiconnect-f3e0f',
    storageBucket: 'ugiconnect-f3e0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOpp1IJfq3k8bzpr_jwKbF7UJ42pNUIMs',
    appId: '1:443807882531:ios:e478e781856c6059c68096',
    messagingSenderId: '443807882531',
    projectId: 'ugiconnect-f3e0f',
    storageBucket: 'ugiconnect-f3e0f.appspot.com',
    iosClientId: '443807882531-hmn1nefackblot522a9sdpoeclvvom27.apps.googleusercontent.com',
    iosBundleId: 'com.example.alpha',
  );
}
